# Generated by Django 2.2.5 on 2020-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_friend_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='continuous_login',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
