# Generated by Django 2.2.5 on 2020-05-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200512_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_products',
            field=models.ManyToManyField(blank=True, to='ecapp.Product'),
        ),
    ]
