# Generated by Django 2.2.5 on 2020-05-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200512_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='static/default_icon.jpg', upload_to='icons'),
        ),
    ]
