# Generated by Django 2.2.5 on 2020-05-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200522_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
