# Generated by Django 2.2.5 on 2020-07-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200716_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='test name', max_length=50, verbose_name='ユーザー名'),
            preserve_default=False,
        ),
    ]
