# Generated by Django 2.2.5 on 2020-04-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='created_at',
            new_name='pushed_date',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='user',
            new_name='pusher',
        ),
    ]
