# Generated by Django 2.2.5 on 2020-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0005_auto_20200505_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
