# Generated by Django 2.2.5 on 2020-06-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0006_auto_20200603_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='evaluate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
