# Generated by Django 2.2.5 on 2020-06-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0007_article_evaluate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='evaluate',
            new_name='evaluation',
        ),
    ]
